config/routes.rb
Rails.application.routes.draw do

  get 'home/home'
  get 'home/radioselect' => 'home#radioselect'

  get 'home/yourbuses'=> 'home#yourbuses'

  get 'home/busesarriving'=>'home#yourbuses_dropdown'

  root 'home#home'

  resources :selections

  resources :stations

end

app/models/selection.rb
class Selection < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

#we're going to be using a method we created in the application_helper.rb
include ApplicationHelper

#the next two lines are required to access the API
require 'open-uri'
require 'json'

#home/home
#a landing page

  def home
    # @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)
  end

#action/page where the userwill use radio buttons

  def radioselect
    # an array of all the MARTA stations
    @stations = ["North Springs", "Hamilton E. Holmes", "Lindbergh", "Midtown", "Georgia State", "Reynoldstown/Inman Park", "Dunwoody", "Lenox", "Sandy Springs", "Medical Center", "Doraville", "Chamblee", "Brookhaven/Oglethorpe", "Arts Center", "North Avenue", "Civic Center", "Ashby", "Peachtree Center", "Vine City", "West End", "Airport", "College Park", "East Point", "Philips Arena/CNN Center", "Garnett", "West Lake", "Bankhead", "Oakland City", "Lakewood/Ft. McPherson", "King Memorial", "Avondale", "East Lake", "Kensington", "Decatur", "Indian Creek", "Edgewood/Candler Park", "Inman Park/Reynoldstown", "Buckhead"]
    # @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)

   #sort the stations alphabetically

   @stations = @stations.sort_by{|item| item.downcase}

  end

  #page where the coming buses will be displayed, after the radio button choice
  def yourbuses
    #the passed parameter is set to an instance variable
    @station = params[:station]
    
    #here we pull the real-time info from MARTA and put it into a hash. Copy and paste the URL and and familiarize yourself with what data is in there.

    @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)

    hash_and_msg_generator(@results, @station) # find this method in the Application Helper
  end

#page where coming buses will be displayed as dropdowns
  def yourbuses_dropdown
    yourstation = Selection.last

    @selection = yourstation.station_name
    @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)
    
    hash_and_msg_generator(@results, @station) # find this method in the Application Helper
  end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        #redirect the path below!
        format.html { redirect_to home_busesarriving_path, notice: 'Selection was successfully created.' }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:station_name)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#this is where the User's selection -- 'station'-- will compared with the API data -- 'results'
	def hash_and_msg_generator(results, station)
		#we will have a couple messages to tell the user whether or not a bus is coming soon
		  @message = ""

		#we want to provide the user with the Route and Vehicle numbers for the approaching bus(es). the best way to save two related items is in a hash!
		@buses = {}
		results.each do |result|
			if result["TIMEPOINT"].include?station
				@buses[result["ROUTE"]]= result["VEHICLE"]
				#the Route is the key and the vehicle is the value
			end

		end
		if @buses.count==0
			#no buses have the User's station as their next stop
			@message = "Sorry, it's gonna be a while."
		elsif @buses.count == 1
			#one bus will be making the connection to the User's station
			@message = "A bus is on its way!"
		elsif @buses.count > 1
			@message  = "These buses will be coming soon:"
		else
			#just in case there is a negative number
			@message  = "Oops... I think there was a slight error"
		end

	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/home/home.html.erb
<div>
	There are <%= @results.count %> bus routes currently.

	<%  @results.each do |r|  %>
	    latitude <%= r['LATITUDE']  %><br>
	    longitude <%= r['LONGITUDE']  %><br>
	    <hr>
	    <%  end  %>
</div>

app/views/home/radioselect.html.erb
<!--
	All the CSS classes are optional, and can be found in the application.css file, which you can copy from GitHub
-->

<!-- <div class ="scroll choose-a-station"> -->

	<div class="title"><h2> Choose a Station!</h2></div>
	<div class= "where"><p><b>Where are you?</b></p></div>
<!-- </div>
 -->

<div class = "radios">
	<!--Below is the form for RAdio Buttons -->
	<ul>
	<%= form_tag("/home/yourbuses", method: "get") do  %>
	<%= label_tag(:station, "")  %>
	<br>

	<%  @stations.each do |station|  %>
	
	  <!-- Loop through the array-->
	  <li><%= radio_button_tag(:station, station) %><span class= "select"><%= station %></span></li>
	  <%  end  %>
	
	  <span class="submit"><%= submit_tag 'Check for buses!', :class => 'btn submit-button'  %></span>
	  <%  end  %>
	  </ul>
	</div>
<div class="results">
	<% @results.each do |r| %>
		<% if r['TIMEPOINT'].include? "Inman Park" %>
		  <%= r['ROUTE'] + " will be stopping at Inman Park Station." %> <br />
		  <hr>
		<% end %>
	<% end %>
</div>

app/views/home/yourbuses.html.erb
<!--
	Here we'll see the results of the user's radio-button choice
	-->

	<h3>
		You are at <%= @station  %> Station
	</h3>
	
	<div>
		<%= @message  %>
		<!-- Here is the message we set up in the Application Helper-->
	</div>
	<br>
	<%  @buses.each do |route, vehicle|  %>
	  <!-- We loop through the hash, printing out keys and values. 
	  If nothing is in the hash, nothing will print out. No harm no foul. -->
	  <div>
	  	Route: <%= route  %><br>
	  	Vehicle: <%= vehicle  %><br>
	  </div>
	  <hr/>
	  <%  end  %>

app/views/home/yourbuses_dropdown.html.erb
<!--
	This is the sister-page of yourbuses.html.erb
	This handles the results from the dropdown menu choice
	-->
	<h3>
      You are at <%= @selection  %> Station.
	</h3>

	<div>
      <%= @message  %>
	</div>
	<br>

	<%  @buses.each do |route, vehicle|  %>
	<div>
      Route: <%= route  %><br>
      Vehicle: <%= vehicle  %><br>
	</div>

	<hr>
	<%  end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>MartApp :)</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/skeleton.css">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="images/favicon.png" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>


</body>
</html>

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- We're just gonna have one field to select a station name -->

  <div class="field">
    <!-- Below is the tag for a drop-down menu-->
    <%= f.select :station_name, Station.all.collect{|station| [station.name]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1>Listing selections</h1>

<table>
  <thead>
    <tr>
      <th>Station name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.station_name %></td>
        <td><%= link_to 'Show', selection %></td>
        <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
        <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station name:</strong>
  <%= @selection.station_name %>
</p>

<% @results.each do |result| %>

  <% if result['TIMEPOINT'].include? @selection.station_name %>

    <%= result['ROUTE'] + " will be stopping at #{@selection.station_name}." %> <br />

    <hr>

  <% end %>

<% end %>
<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>